apiVersion: v1
kind: Service
metadata:
  name: tempo-web-service
  labels:
    app: tempo-web
spec:
  type: NodePort
  selector:
    app: tempo-web
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
      protocol: TCP
      name: http